/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RotasRouteImport } from './routes/rotas'
import { Route as RemessasRouteImport } from './routes/remessas'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as FrotaRouteImport } from './routes/frota'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as IndexRouteImport } from './routes/index'

const RotasRoute = RotasRouteImport.update({
  id: '/rotas',
  path: '/rotas',
  getParentRoute: () => rootRouteImport,
} as any)
const RemessasRoute = RemessasRouteImport.update({
  id: '/remessas',
  path: '/remessas',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const FrotaRoute = FrotaRouteImport.update({
  id: '/frota',
  path: '/frota',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/frota': typeof FrotaRoute
  '/relatorios': typeof RelatoriosRoute
  '/remessas': typeof RemessasRoute
  '/rotas': typeof RotasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/frota': typeof FrotaRoute
  '/relatorios': typeof RelatoriosRoute
  '/remessas': typeof RemessasRoute
  '/rotas': typeof RotasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/frota': typeof FrotaRoute
  '/relatorios': typeof RelatoriosRoute
  '/remessas': typeof RemessasRoute
  '/rotas': typeof RotasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clientes'
    | '/configuracoes'
    | '/frota'
    | '/relatorios'
    | '/remessas'
    | '/rotas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clientes'
    | '/configuracoes'
    | '/frota'
    | '/relatorios'
    | '/remessas'
    | '/rotas'
  id:
    | '__root__'
    | '/'
    | '/clientes'
    | '/configuracoes'
    | '/frota'
    | '/relatorios'
    | '/remessas'
    | '/rotas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientesRoute: typeof ClientesRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  FrotaRoute: typeof FrotaRoute
  RelatoriosRoute: typeof RelatoriosRoute
  RemessasRoute: typeof RemessasRoute
  RotasRoute: typeof RotasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rotas': {
      id: '/rotas'
      path: '/rotas'
      fullPath: '/rotas'
      preLoaderRoute: typeof RotasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/remessas': {
      id: '/remessas'
      path: '/remessas'
      fullPath: '/remessas'
      preLoaderRoute: typeof RemessasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frota': {
      id: '/frota'
      path: '/frota'
      fullPath: '/frota'
      preLoaderRoute: typeof FrotaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientesRoute: ClientesRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  FrotaRoute: FrotaRoute,
  RelatoriosRoute: RelatoriosRoute,
  RemessasRoute: RemessasRoute,
  RotasRoute: RotasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
